spring:
  profiles:
    active: local
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
#  thymeleaf:
#    mode: HTML5
#    cache: false
#    templates_root: classpath:/templates/
#   templates_root: src/main/resources/templates/


