spring:
  database:
    cms:
      datasource:
          platform: oracle
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=116.126.69.112)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=BTEST)))
          username: HANAROCMS
          password: Tl0408dpadptm
          initialize: true
          max-active: 20
          max-idle: 10
          max-wait: -1
          validation-query: SELECT 1 FROM dual
    redis:
      hosts:
        -
          host: 127.0.0.1
          port: 7000
        -
          host: 127.0.0.1
          port: 7001
        -
          host: 127.0.0.1
          port: 7002
        -
          host: 127.0.0.1
          port: 7003
        -
          host: 127.0.0.1
          port: 7004
        -
          host: 127.0.0.1
          port: 7005
      timeout: 3000
      pool:
        max-active: 30
        max-idle: 10
        max-wait: -1
        min-idle: 0
  common:
    default-license-key: 1:00000000000000,2:00000000000000,3:00000000000000,4:00000000000000,5:00000000000000
    sync:
      iptvinfo: /iptvchlicense/IptvCHLicenseInfo.jsp?
      manager: /iptvchlicense/manager.jsp?
      licupdate: /iptvchlicense/licupdate.jsp?