spring:
  cms:
    datasource:
        platform: oracle
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=116.126.69.112)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=BTEST)))
        username: HANAROCMS
        password: Tl0408dpadptm
        initialize: true
        max-active: 20
        max-idle: 10
        max-wait: -1
        validation-query: SELECT 1 FROM dual
  redis:
    host: 127.0.0.1
    database: 0
    password: svc24bm
    pool:
      max-active: 30
      max-idle: 10
      max-wait: -1
      min-idle: 0
    timeout: 3000
    port: 6379
  redis-slave:
    host: 127.0.0.1
    database: 0
    pool:
      max-active: 30
      max-idle: 10
      max-wait: -1
      min-idle: 0
    timeout: 3000
    port: 6389





